update - prompt for missing domain and push pw to clipboard

diff --git a/pwcomposer b/pwcomposer
--- a/pwcomposer
+++ b/pwcomposer
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 MD5=`which md5sum`
 if [ ! -x "$MD5" ]
 then
@@ -11,15 +10,24 @@ then
     exit 1
 fi
 
-if [ $# -ne 1 ]
+#XCLIP=`which xclip`
+XCLIP=`which pbcopy`
+if [ ! -x "$XCLIP" ]
 then
-    echo "Usage:" >&2
-    echo -n `basename $0` >&2
-    echo " <password site> (host name, like \"www.example.com\")" >&2
+    echo "Utility xclip not found." >&2
     exit 1
 fi
 
-echo "Enter password (will not echo)"
+if [ $# -ne 1 ]
+then
+    echo -n "Enter the domain> "
+    read DOMAIN
+else
+    DOMAIN=$1
+fi
+
+echo -n "Enter your master password> "
 stty -echo
-head -1 | cat - <(echo :$1) - | tr -d \\n | $MD5 | cut -b 1-8
+echo -n "$(head -1 | cat - <(echo :$DOMAIN) - | tr -d \\n | $MD5 | cut -b 1-8)" | $XCLIP
 stty echo
+echo -e "\nPassword has been copied to clipboard"
